version: '3'

networks:
  app:
    driver: bridge

services:
  rest-server:
    build: cmd/rest
    volumes:
      - .:/go/src/simbir-rest
    working_dir: /go/src/simbir-rest
    depends_on:
      - postgres
    hostname: rest
    restart: on-failure
    ports:
      - "5000:5000"
    environment:
      - REST_SERVER_DB=postgres://simbir:simbir@postgres/simbir_db?sslmode=disable
      - REST_SERVER_HOST=:5000
      - REST_SERVER_LOGGER=1
      - LOG_FILE=./logs/application.log
    networks:
      - app

  postgres:
    image: postgres:11.1
    restart: on-failure
    environment:
      POSTGRES_USER: simbir
      POSTGRES_PASSWORD: simbir
      POSTGRES_DB: simbir_db
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - app
